name: bong
description: A music player.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.0.0
  animated_size_and_fade: ^3.0.0
  persian_flutter: ^0.2.0
  persian_number_utility: ^1.1.1
  flutter_easyloading: ^3.0.3
  rxdart: ^0.27.3
  persian_tools: ^1.0.1
  camera: ^0.10.0+4
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  infinite_scroll_pagination: ^3.2.0
  flashy_tab_bar2: ^0.0.4
  animated_switcher_plus: ^1.0.2
  loading_animation_widget: ^1.2.0+3
  animations: ^2.0.7
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.8
  flutter_cache_manager: ^3.3.0
  audio_video_progress_bar: ^0.11.0
  chewie: ^1.3.5
  video_player: ^2.4.7
  lottie: ^2.0.0
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6
  # connectivity_plus: ^3.0.0
  cached_network_image: ^3.2.3
  stretchy_header: ^2.0.0
  story_view: ^0.14.0
  # flutter_downloader: ^1.9.1
  bubble_tab_indicator: ^0.1.6
  path_provider: ^2.0.11
  rflutter_alert: ^2.0.4
  flutter_datetime_picker: ^1.5.1
  url_launcher: ^6.1.7







dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.11.0"
  change_app_package_name: ^1.1.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-min.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: iran
      fonts:
        - asset: assets/fonts/IRANSansMobile(FaNum)_UltraLight.ttf
          weight: 100
        - asset: assets/fonts/IRANSansMobile(FaNum)_Light.ttf
          weight: 200
        - asset: assets/fonts/IRANSansMobile(FaNum)_Medium.ttf
          weight: 300
        - asset: assets/fonts/IRANSansMobile(FaNum)_Black.ttf
          weight: 400
        - asset: assets/fonts/IRANSansMobile(FaNum)_Bold.ttf
          weight: 500